name: Cowsay

on: push
jobs:
  Ascii_job :
    runs-on: ubuntu-latest
    steps:
      - 
        name: install cowsay program
        run: sudo apt-get install cowsay -y

      -
        name: Execute cowsay CMD
        run: cowsay -f dragon "Run for cover, iam a Dragon....RAWR" >> dragon.txt
      
      -
        name: Test File Exists
        run: grep -i "dragon" dragon.txt

      -
        name: Read File
        run: cat dragon.txt

      -
        name: checkout repo files 
        run: ls
