name: Cowsay

on: push
jobs:
  Ascii_job :
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v6.0.2

      -
        name: run script
        run: |
          chmod +x cowsay.sh
          ./cowsay.sh
      
   