name: using matrix strategy

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      matrix: 
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        image: [hello-world, alpine]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo Docker details
        run: docker info
      - name: Run image
        run: docker run ${{ matrix.image }}
