name: x-workflow
on : 
      push:
        branches:
          - main

jobs:
  docker :
    runs-on: ubuntu-latest
    steps:
      - 
        name: echo name
        run: echo "Youssef Said"


